# Generated by Django 4.1.2 on 2022-10-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcategory',
            old_name='book_category',
            new_name='name',
        ),
    ]
